"""Render a standalone, self-contained interactive HTML prototype.

One file, inline CSS/JS, no external dependencies — it opens from the vault and
works offline. Items are browsable and filterable by provenance (grounded /
derived / model knowledge), reinforcing the fidelity story visually.
"""

from __future__ import annotations

import json

from jinja2 import Template

from r2a.pipeline.stage import StageContext

_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ title }}</title>
<style>
  :root { --ink:#222; --muted:#6b6b6b; --line:#e3e0d8; --bg:#faf9f6; --accent:#9a5b3f; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--ink);
         font:16px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; }
  main { max-width:760px; margin:0 auto; padding:2.5rem 1.25rem 4rem; }
  h1 { font-size:1.7rem; margin:0 0 .25rem; }
  .src { color:var(--muted); margin:0 0 1.5rem; }
  .summary { border-left:3px solid var(--accent); padding:.25rem 0 .25rem 1rem; margin:0 0 1.5rem; }
  .filters { display:flex; gap:.5rem; flex-wrap:wrap; margin-bottom:1.25rem; }
  .filters button { border:1px solid var(--line); background:#fff; color:var(--ink);
                    padding:.35rem .8rem; border-radius:999px; cursor:pointer; font-size:.85rem; }
  .filters button.active { background:var(--ink); color:#fff; border-color:var(--ink); }
  .card { border:1px solid var(--line); background:#fff; border-radius:10px;
          padding:1rem 1.1rem; margin-bottom:.85rem; }
  .card p { margin:0 0 .5rem; }
  .badges { display:flex; gap:.4rem; flex-wrap:wrap; }
  .badge { font-size:.72rem; padding:.12rem .55rem; border-radius:999px; border:1px solid var(--line);
           color:var(--muted); }
  .badge.derived { color:var(--accent); border-color:var(--accent); }
  .cites { font-size:.78rem; color:var(--muted); margin-top:.4rem; }
  footer { color:var(--muted); font-size:.78rem; margin-top:2rem; }
</style>
</head>
<body>
<main>
  <h1>{{ title }}</h1>
  <p class="src">From {{ source }}</p>
  {% if summary %}<div class="summary">{{ summary }}</div>{% endif %}
  <div class="filters">
    <button data-f="all" class="active">All ({{ items|length }})</button>
    <button data-f="grounded">Grounded</button>
    <button data-f="derived">Derived</button>
    <button data-f="model">Model knowledge</button>
  </div>
  <div id="list"></div>
  <footer>Generated by Research to Artifact — every grounded item traces to a source bite.</footer>
</main>
<script>
const ITEMS = {{ items_json }};
const list = document.getElementById('list');
function render(filter) {
  list.innerHTML = '';
  for (const it of ITEMS) {
    if (filter === 'grounded' && (it.derived || it.model_knowledge)) continue;
    if (filter === 'derived' && !it.derived) continue;
    if (filter === 'model' && !it.model_knowledge) continue;
    const card = document.createElement('div');
    card.className = 'card';
    const p = document.createElement('p'); p.textContent = it.text; card.appendChild(p);
    const badges = document.createElement('div'); badges.className = 'badges';
    if (it.derived) badges.innerHTML += '<span class="badge derived">derived</span>';
    if (it.model_knowledge) badges.innerHTML += '<span class="badge">model knowledge</span>';
    if (it.cites.length) badges.innerHTML += '<span class="badge">' + it.cites.length + ' citation(s)</span>';
    card.appendChild(badges);
    if (it.cites.length) {
      const c = document.createElement('div'); c.className = 'cites';
      c.textContent = 'Bites: ' + it.cites.join(', '); card.appendChild(c);
    }
    list.appendChild(card);
  }
}
document.querySelectorAll('.filters button').forEach(b => b.addEventListener('click', () => {
  document.querySelectorAll('.filters button').forEach(x => x.classList.remove('active'));
  b.classList.add('active'); render(b.dataset.f);
}));
render('all');
</script>
</body>
</html>
"""
)


def render_html(ctx: StageContext) -> str:
    draft = ctx.draft
    assert draft is not None
    source = ctx.retrieved[0].bite.source_title if ctx.retrieved else "the import"
    items = [
        {
            "text": it.text,
            "cites": it.cites,
            "derived": it.derived,
            "model_knowledge": it.model_knowledge,
            "web_sources": it.web_sources,
        }
        for it in draft.items
    ]
    return _TEMPLATE.render(
        title=draft.title,
        source=source,
        summary=draft.summary,
        items=items,
        items_json=json.dumps(items),
    )
